name: Codeless Builder

on: [push]
jobs:

publish-hello-docker-image:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry

uses: docker/login-action@v1
with:

registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.TOKEN }}
  - name: Build Docker image

run: |
       docker build . --tag ghcr.io/codeless-builder/codeless-builder:latest
       docker run ghcr.io/codeless-builder/codeless-builder:latest
       docker push ghcr.io/codeless-builder/codeless-builder:latest